### PR TITLE
Fix minor typo

### PR DESCRIPTION
**Pull request by pombredanne**
Signed-off-by: Philippe Ombredanne <pombredanne@nexb.com>

### CODE REVIEW

**Comment by R2wenD2** [comment]
@pombredanne do you want to rebase this so I can merge?

**Comment by pombredanne** [comment]
done!

**Comment by R2wenD2** [comment]
This one also needs a rebase :) I'll merge right away again.

**Comment by pombredanne** [comment]
rebased again :P

**Pull request merged**
