### PR TITLE
add missing call to validatePageSize in ListNoteOccurrences

### PR DESCRIPTION
**Pull request by th3w4y**
Issue: 

the func (g *API) ListNoteOccurrences does not use validatePageSize(req.PageSize) but req.PageSize in its call to g.Storage.ListNoteOccurrences() 

This potentially results in an [] empty response due to the use of LIMIT = pageSize in the queries.go, which gets set to 0 (unspecified default req.PageSize) 

cc: @aysylu @wkozlik 

* add pageSize validation to ListNoteOccurrences
* regenerated files after comment change in PR #454
* allow cel/syntax.pb.go so that stg. engines be able to import github.com/grafeas/grafes/cel for filter implementation

### CODE REVIEW

**Comment by th3w4y** [comment]
After the proposed fixed one can successfully use ListNoteOccurrences.

```
curl http://localhost:8080/v1beta1/projects/secret-project/notes/demo/occurrences | jq
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 11861    0 11861    0     0  2316k      0 --:--:-- --:--:-- --:--:-- 2316k
{
  "occurrences": [
    {
      "name": "projects/secret-project/occurrences/80556e60-1922-4b7b-a3d5-de674a00157b",
      "resource": {
        "name": "",
        "uri": "projects/secret-project/notes/demo",
        "contentHash": null
      },
      "noteName": "projects/secret-project/notes/demo",
      "kind": "BUILD",
      "remediation": "",
      "createTime": "2020-10-20T17:30:28.335301Z",
      "updateTime": null,
      "build": {
        "provenance": {
          "id": "demo",
          "projectId": "secret-project",
          "commands": [],
...
```
[potentially fixing the pageSize part of the behaviour described in #343]

**Comment by wkozlik** [comment]
Thank you for the fix. Could you add a unit test to validate page size?

**Comment by th3w4y** [comment]
this PR would only introduce consistency as all other methods defined by API are calling the validatePageSize(req.PageSize) without such unit tests...

if i am to add tests for validatePageSize the blast of the change gets way bigger, testing the empty zero value of req.pageSize would most likely require some modification of behaviour in the fakeStorage to return [] in such event, and this might affect more use-cases.


i suggest if possible merge the PR as such as it brings the consistency (validatePageSize(req.PageSize) was missed from that method in the past) then i will think of a way to verify the unit-test arround validations of zero-values generated by the protos vs the conventions value of what we would expect the defaults to be as per the comments in the .proto files.

**Comment by th3w4y** [comment]
a follow up for the unit-tests https://github.com/grafeas/grafeas/issues/459

**Comment by wkozlik** [comment]
The existing test for ListOccurrences (https://github.com/grafeas/grafeas/blob/f11fa45f2a57406a0b69eb3463ecbca9e127ccd2/go/v1beta1/api/occurrence_test.go#L191) covers page size validation. I was thinking about adding a similar test case in https://github.com/grafeas/grafeas/blob/f11fa45f2a57406a0b69eb3463ecbca9e127ccd2/go/v1beta1/api/occurrence_test.go#L749. Would that work?

**Comment by th3w4y** [comment]
looking into the unit-test, but not sure that can be captured under TestListNoteOccurrencesErrors, as pagesize = 0 should be rewritten to defaultPageSize = 20 and will not produce an err.

**Review by wkozlik — APPROVED** [review]
LGTM
Thank you for the fix and being very thorough.

**Pull request merged**
