### PR TITLE
grafeas.proto: Document key purpose in notes map

### PR DESCRIPTION
**Pull request by c4milo**

### CODE REVIEW

**Review by aysylu — APPROVED** [review]
thanks for the improvement!

**Comment by aysylu** [comment]
Hi @c4milo, this branch was out-of-sync w/master, so I used the automated GH feature to sync them, which triggered the re-run of tests but they haven't completed in some time. Could you please re-push the changes to trigger the tests on your end, so hopefully we can merge this sooner? Thanks!

**Comment by c4milo** [comment]
@aysylu, done. Thanks!

**Comment by c4milo** [comment]
seems to be failing building the docker image: 

Screen Shot 2020-09-17 at 3 45 09 PM

**Comment by aysylu** [comment]
@c4milo: it looks like this was a transient issue? The tests are now passing so I'll merge this PR. Thanks for your contribution!

**Pull request merged**
