### PR TITLE
add dsse envelope proto message to v1beta1 APIs

### PR DESCRIPTION
**Pull request by hkadakia**

### CODE REVIEW

**Comment by aysylu** [comment]
Hi @hkadakia, is the intention to also use these DSSE Envelopes on the top-level of Occurrences?

**Comment by hkadakia** [comment]
> Hi @hkadakia, is the intention to also use these DSSE Envelopes on the top-level of Occurrences?

Yes. I updated the PR to add envelope as part of the top-level Occurrence.

**Review by aysylu — APPROVED** [review]
LGTM. Will wait for @wkozlik and @patricklawsongoogle to TAL as well, before merging.

**Review by wkozlik — APPROVED** [review]

**Comment by patricklawsongoogle** [comment]
LGTM

**Pull request merged**
