### PR TITLE
Temporarily remove `go vet` from the `build` command

### PR DESCRIPTION
**Pull request by aysylu**
Addresses #308 . #310 is filed to investigate and re-enable.

### CODE REVIEW

**Comment by vtsao** [comment]
Can you elaborate on the issues you're running into with vet? Also, what are the issues we run into that require us to set composites to false? It should always be true. Unless protoc generates proto bindings that violate that style rule? Which I don't think it does?

**Comment by aysylu** [comment]
Yes, `composites=false` was set in #266, idea from [this thread](https://stackoverflow.com/questions/36273920/disable-go-vet-checks-for-composite-literal-uses-unkeyed-fields). The issue with `vet` that inspired this PR is described in #310.

**Comment by vtsao** [comment]
I still don't understand what is not using keyed literals that we need to set composites to false for?

Also, let's confirm he's running into a Docker issue and not make. The log he posted is from Docker build command.

**Comment by aysylu** [comment]
Withdrawing the PR for now, as it's not solving the root cause and I won't be able to get to this by the end of the month. I'll follow up with the reason for the vet directive flag directly with @vtsao

**Pull request closed without merging**
