### PR TITLE
upgrade to grpc-gateway/v2@v2.7.0

### LINKED ISSUE #522: Updating repeated fields is broken due to grpc-gateway bug
## Background
Grafeas is impact by this bug: https://github.com/grpc-ecosystem/grpc-gateway/pull/1921, which was released in [2.3.0](https://github.com/grpc-ecosystem/grpc-gateway/releases/tag/v2.3.0), but grafeas is on [2.0.1](https://github.com/grafeas/grafeas/blob/master/go.mod#L17)

## Expected Behavior
Updating an occurrence should allow for a list of repeated fields to be appended to the existing fields.

## Actual Behavior
Updating an occurrence returns an error if you update a repeated field.

```
{\"code\":3,\"message\":\"only one repeated value is allowed per field_mask\"}: 400 Bad Request"
```

### PR DESCRIPTION
**Pull request by aethanol**
Resolves #522

### CODE REVIEW

**Review by aysylu — APPROVED** [review]

**Comment by aysylu** [comment]
Thanks for fixing, @aethanol! Would you mind signing the CLA and pinging this thread when you've done so? Also, do we need to update the generated clients now with the new version?

**Comment by aethanol** [comment]
Ah yeah, I think I hadn't been yet added to the company CLA. Could you try re-running it the check?

For the generated clients are you referring to: https://github.com/grafeas/client-java client-go etc? Yeah I think they will need to be re-generated.

Additionally: are tagged releases still being made? I was seeing that 0.1.6 was released over a year ago.

**Comment by aysylu** [comment]
@aethanol it's showing that it's still missing the CLA, after I re-ran it just now. Perhaps there's a propagation delay?

Re releases: yes, I'm planning on making the release before EOY, hopefully next week (waiting for a couple outstanding changes to land to release it altogether).

**Comment by aethanol** [comment]
@aysylu ah I see what is happening, I opened the PR with my personal account which hadn't accepted the CLA. Can you try again now?

**Comment by aethanol** [comment]
re: > For the generated clients are you referring to: https://github.com/grafeas/client-java client-go etc?

is that what you were meaning?

**Comment by aysylu** [comment]
> re: > For the generated clients are you referring to: https://github.com/grafeas/client-java client-go etc?
> 
> is that what you were meaning?

yes, exactly

**Pull request merged**
