### PR TITLE
Fix error message in CreateNote of memstore.go

### PR DESCRIPTION
**Pull request by antweiss**

### CODE REVIEW

**Comment by antweiss** [comment]
I signed it!

**Comment by vtsao** [comment]
Looks like the CLA check isn't passing, can you please doublecheck that you've followed all the CLA instructions again. Thanks.

**Comment by antweiss** [comment]
The CLA looks fine on my side. Signed it both for my company and for my private account. My github profile and the commit are under the same account as the one I signed the CLA for.
Any way to get this rerun the CLA check?

**Comment by antweiss** [comment]
Ok, worked now! Had to use the CLA email as the primary github account email.

**Pull request merged**
