### PR TITLE
Switch grafeas to go modules.

### PR DESCRIPTION
**Pull request by clrprod**
Specifically
- Make a protodeps folder and check in our proto deps as ~~git submodules~~ go generate commands.
- Update the protoc version, since googleapis isn't compatible with
protoc 3.3.0.
- Rewrite all the proto dep paths
- Remove vendor folder

### CODE REVIEW

**Comment by aysylu** [comment]
Could you please pull the latest changes, resolve conflicts and push to the branch again? Happy to review and merge, since `0.1.0` is now out.

**Comment by clrprod** [comment]
@aysylu I rebased the cl - and it's working locally. Should be good for review.

**Comment by aysylu** [comment]
Hey @clrprod, it looks like some [tests are failing](https://circleci.com/gh/grafeas/grafeas/1337?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link), could you please TAL?

**Comment by clrprod** [comment]
@aysylu It was a timeout while pulling modules - I've repushed to retrigger circleci and it should be fixed. In go 1.13 (which isn't released), this will go through a go proxy that likely has higher uptime than the module source.

**Comment by clrprod** [comment]
@aysylu It passed

**Pull request merged**
