### PR TITLE
Fix for Issue https://github.com/Grafeas/Grafeas/issues/82.

### PR DESCRIPTION
**Pull request by shrajfr12**
For occurrence, all fields in details have the Details suffix. For note however, neither making them all Details suffix nor making them all Type suffix seemed to match the name/usage pattern, so left them unchanged for now. Also protoc  3.5 on macOS would not compile as it was not finding the google/protobuf/*.proto (ubuntu was fine) so added the -I./include in Makefile so that we can build on macOS or ubuntu. Can change the note types also based on the feedback.

### CODE REVIEW

**Comment by R2wenD2** [comment]
@shrajfr12 There should be changes to the generated files as well that you should check in.

**Comment by shrajfr12** [comment]
Was not sure if generated files need to be checked in. Will do soon. Thx.

**Comment by shrajfr12** [comment]
I see three files with new timestamps which are  grafeas.pb.go, grafeas.swagger.json and grafeas.pb.gw.go, but "git status" showed only the two files grafeas.pb.go and grafeas.swagger.json that could be committed so have included only those two.

**Comment by R2wenD2** [comment]
@shrajfr12 Apologies for the delay here. Please update the branch and I'll merge.

**Pull request merged**
