### PR TITLE
Fix gRPC code generation in Java

### PR DESCRIPTION
**Pull request by c4milo**
by making sure the intoto file name matches the class name generated.

Here are the compilation errors I get without this patch: 

```
caguilar at NYC-M-CAGUILAR01 in ~/src/grafeas-java on master [?]
$ ./gradlew build

> Task :compileJava FAILED
/Users/caguilar/src/grafeas-java/build/generated/source/proto/main/java/io/grafeas/v1beta1/intoto/InToto.java:6: error: class Intoto is public, should be declared in a file named Intoto.java
public final class Intoto {
             ^
/Users/caguilar/src/grafeas-java/build/generated/source/proto/main/java/io/grafeas/v1beta1/Note.java:4420: error: cannot find symbol
        io.grafeas.v1beta1.intoto.InToto, io.grafeas.v1beta1.intoto.InToto.Builder, io.grafeas.v1beta1.intoto.InTotoOrBuilder> intotoBuilder_;
                                 ^
  symbol:   class InToto
  location: package io.grafeas.v1beta1.intoto
/Users/caguilar/src/grafeas-java/build/generated/source/proto/main/java/io/grafeas/v1beta1/Note.java:4420: error: package io.grafeas.v1beta1.intoto.InToto does not exist
        io.grafeas.v1beta1.intoto.InToto, io.grafeas.v1beta1.intoto.InToto.Builder, io.grafeas.v1beta1.intoto.InTotoOrBuilder> intotoBuilder_;
                                                                          ^
/Users/caguilar/src/grafeas-java/build/generated/source/proto/main/java/io/grafeas/v1beta1/Note.java:4442: error: cannot find symbol
    public io.grafeas.v1beta1.intoto.InToto getIntoto() {
                                    ^
  symbol:   class InToto
  location: package io.grafeas.v1beta1.intoto
/Users/caguilar/src/grafeas-java/build/generated/source/proto/main/java/io/grafeas/v1beta1/Note.java:4462: error: cannot find symbol
    public Builder setIntoto(io.grafeas.v1beta1.intoto.InToto value) {
                                                      ^
  symbol:   class InToto
  location: package io.grafeas.v1beta1.intoto
/Users/caguilar/src/grafeas-java/build/generated/source/proto/main/java/io/grafeas/v1beta1/Note.java:4483: error: package io.grafeas.v1beta1.intoto.InToto does not exist
        io.grafeas.v1beta1.intoto.InToto.Builder builderForValue) {
                                        ^
/Users/caguilar/src/grafeas-java/build/generated/source/proto/main/java/io/grafeas/v1beta1/Note.java:4500: error: cannot find symbol
    public Builder mergeIntoto(io.grafeas.v1beta1.intoto.InToto value) {
                                                        ^
  symbol:   class InToto
  location: package io.grafeas.v1beta1.intoto
/Users/caguilar/src/grafeas-java/build/generated/source/proto/main/java/io/grafeas/v1beta1/Note.java:4549: error: package io.grafeas.v1beta1.intoto.InToto does not exist
    public io.grafeas.v1beta1.intoto.InToto.Builder getIntotoBuilder() {
                                           ^
/Users/caguilar/src/grafeas-java/build/generated/source/proto/main/java/io/grafeas/v1beta1/Note.java:4578: error: cannot find symbol
        io.grafeas.v1beta1.intoto.InToto, io.grafeas.v1beta1.intoto.InToto.Builder, io.grafeas.v1beta1.intoto.InTotoOrBuilder>
                                 ^
  symbol:   class InToto
  location: package io.grafeas.v1beta1.intoto
```

### CODE REVIEW

**Comment by wkozlik** [comment]
Would it be possible to fix the class name generation by adding the `java_outer_classname` option in intoto.proto? i.e. 
```
option java_outer_classname = "InTotoOuterClass";
```

This would avoid renaming files, which would be a braking change.

See https://developers.google.com/protocol-buffers/docs/javatutorial?hl=en

**Comment by c4milo** [comment]
@wkozlik, it doesn't seem to work: 

```
Execution failed for task ':generateProto'.
> protoc: stdout: . stderr: --java_out: proto/v1beta1/intoto.proto: proto/v1beta1/intoto.proto: Cannot generate Java output because the file's outer class name, "InToto", matches the name of one of the types declared inside it.  Please either rename the type or use the java_outer_classname option to specify a different outer class name for the .proto file.
```

**Comment by c4milo** [comment]
actually, I spoke too soon, it seems to work.

**Comment by wkozlik** [comment]
Make sure to delete old generated files. This command works for me:
```
$ /usr/local/bin/protoc \
--plugin=protoc-gen-grpc-java=$HOME/protoc-gen-grpc-java-1.28.0-linux-x86_64.exe \
--grpc-java_out=$HOME/go/src/github.com/grafeas/grafeas/java/v1beta1 \
-I . \
-I $HOME/go/src/github.com/googleapis \
--java_out=java/v1beta1 proto/v1beta1/intoto.proto

$ ls $HOME/go/src/github.com/grafeas/grafeas/java/v1beta1/io/grafeas/v1beta1/intoto
Details.java  DetailsOrBuilder.java  InToto.java  InTotoOrBuilder.java  InTotoOuterClass.java  Link.java  LinkOrBuilder.java  Signature.java  SignatureOrBuilder.java  SigningKey.java  SigningKeyOrBuilder.java
```

**Comment by c4milo** [comment]
@wkozlik, yes, I updated the PR with the suggested change. Thanks!

**Review by wkozlik — APPROVED** [review]
LGTM

**Pull request merged**
